openapi: 3.0.0
info:
  title: SISGESC API Documentation
  version: 1.0.0
  description: API documentation for the SISGESC system
  contact:
    name: API Support
    url: https://github.com/SISGESC/sisgesc-api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: []